LPS-191018
igor-franca/liferay-portal pull request #51
Opened 2023-07-27 17:09 UTC by igor-franca

2023-07-27 17:33 UTC, liferay-continuous-integration commented
Closing pull request because pulls for reference model-builder should not be sent to repository liferay-portal

2023-07-28 14:09 UTC, igor-franca commented
ci:reopen

2023-07-31 18:00 UTC, danvb112 requested changes

2023-07-31 18:00 UTC, danvb112 commented on modules/apps/object/object-js-components-web/src/main/resources/META-INF/resources/components/VerticalBar/CustomVerticalBar.scss
> +}
@igor-franca Please speak with me about this

2023-08-10 12:25 UTC, closed without merging